# Generated by Django 5.2.13 on 2026-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_employee_expense_project_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='Starter', max_length=20)),
                ('billing', models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], default='Monthly', max_length=20)),
                ('seats', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Trialing', 'Trialing'), ('PastDue', 'PastDue'), ('Canceled', 'Canceled')], default='Active', max_length=20)),
                ('start_date', models.DateField()),
                ('next_billing', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
